name: ibec3
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10.12
  - numpy
  - scipy
  - h5py
  - pyyaml
  - matplotlib
  - opencv=4.5.5
  - pyqt=5.12
  - qt=5.12
  - pytorch